# 配置服务器端口号
server.port=8080

# 配置 MySQL
spring.datasource.mine.url=jdbc:mysql://127.0.0.1:3306/mysql_transaction?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
spring.datasource.mine.username=root
spring.datasource.mine.password=Yang199001
spring.datasource.mine.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mysql.version=8.0.X

# 配置 MongoDB, 这里和没有取消 MongoDB 的自动注入配置结合使用!
#   连接时出现错误: com.mongodb.MongoSocketOpenException: Exception opening socket
#   改动 mongodb.cnf 中的 bind_ip = 0.0.0.0, 改为远程访问 就OK了!
spring.data.mongodb.uri=mongodb://yangyang:123456@192.168.188.6:27017/mydb

# 配置 MongoDB 日志, 作用: 打印每次操作 MongoDB 的日志
logging.level.org.springframework.data.mongodb=debug

# 配置 Redis
spring.redis.host=192.168.188.7
spring.redis.password=root
spring.redis.port=6379
# 最大连接数, 0表示无限制
spring.redis.pool.max-active=8
