spring.datasource.mine.url=jdbc:mysql://127.0.0.1:3306/orm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
spring.datasource.mine.username=root
spring.datasource.mine.password=Yang199001
spring.datasource.mine.driver-class-name=com.mysql.cj.jdbc.Driver
